# Generated by Django 4.2.5 on 2024-07-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_user_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='likes',
            new_name='posts_liked',
        ),
    ]
