# Generated by Django 4.2.5 on 2024-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
